const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require(process.env.PANOPTICON_PLAYWRIGHT_CORE);
const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PANOPTICON_CHROME||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
 const errors=[];
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
  await page.goto(fixture.url);await page.locator('#login-username').fill('viewer');await page.locator('#login-password').fill(fixture.password);
  await page.getByRole('button',{name:'로그인',exact:true}).click();await page.locator('#login-overlay.hidden').waitFor({state:'attached'});
    await page.locator('#connection-status.connected').waitFor({state:'visible'});
  await page.locator('#tab-btn-ai-analyzer').click();await page.waitForFunction(()=>document.querySelector('#ai-state').textContent==='정지');
  await page.waitForFunction(()=>document.querySelectorAll('#ai-logs-body tr').length===50);
  assert.equal(await page.locator('#ai-provider').textContent(),'copilot');
  assert.equal(await page.locator('#ai-logs-body img').count(),0);assert.equal(await page.evaluate(()=>window.aiInjected),undefined);
  await page.locator('#ai-filter-pagesize').selectOption('100');await page.waitForFunction(()=>document.querySelectorAll('#ai-logs-body tr').length===51);
  await page.evaluate(async()=>{window.aiChecks=await import('/js/modules/ai_analyzer.js');});
  const status='**/api/ai-analyzer/status';
  await page.route(status,r=>r.fulfill({status:503,contentType:'application/json',body:'{}'}));
  await page.evaluate(()=>window.aiChecks.loadAiAnalyzerStatus());assert.equal(await page.locator('#ai-state').textContent(),'상태 확인 불가');assert.equal(await page.locator('#ai-provider').textContent(),'—');
  await page.evaluate(()=>window.i18next.emit('languageChanged','ko'));assert.equal(await page.locator('#ai-state').textContent(),'상태 확인 불가');
  await page.unroute(status);
  await page.route(status,async r=>{const response=await r.fetch();const value=await response.json();value.running=true;await r.fulfill({json:value});});
  await page.evaluate(()=>window.aiChecks.loadAiAnalyzerStatus());assert.equal(await page.locator('#ai-state').textContent(),'상태 확인 불가');await page.unroute(status);
  let release,entered;const held=new Promise(r=>release=r),started=new Promise(r=>entered=r);let calls=0;
  await page.route(status,async r=>{calls++;if(calls===1){const response=await r.fetch();entered();await held;await r.fulfill({response});}else await r.fulfill({status:503,body:'{}'});});
  const old=page.evaluate(()=>window.aiChecks.loadAiAnalyzerStatus());await started;
  await page.evaluate(()=>window.aiChecks.loadAiAnalyzerStatus());release();await old;
  assert.equal(await page.locator('#ai-state').textContent(),'상태 확인 불가');await page.unroute(status);
  await page.evaluate(()=>window.aiChecks.loadAiAnalyzerStatus());assert.equal(await page.locator('#ai-state').textContent(),'정지');
  const logs='**/api/events?*engine=ai_analyzer*';
  await page.route(logs,r=>r.fulfill({status:503,body:'{}'}));await page.evaluate(()=>window.aiChecks.loadAiLogs(0));
  assert.ok((await page.locator('#ai-logs-body').textContent()).includes('불러올 수 없습니다'));assert.equal(await page.locator('#ai-logs-pagination button').count(),0);await page.unroute(logs);
  let releaseLogs,enteredLogs;const heldLogs=new Promise(r=>releaseLogs=r),startedLogs=new Promise(r=>enteredLogs=r);
  let releaseStatus,enteredStatus;const heldStatus=new Promise(r=>releaseStatus=r),startedStatus=new Promise(r=>enteredStatus=r);
  await page.route(logs,async r=>{const response=await r.fetch();enteredLogs();await heldLogs;await r.fulfill({response});});
  await page.route(status,async r=>{const response=await r.fetch();enteredStatus();await heldStatus;await r.fulfill({response});});
  const pending=page.evaluate(()=>Promise.all([window.aiChecks.loadAiLogs(0),window.aiChecks.initAiAnalyzerTab()]));
  await Promise.all([startedLogs,startedStatus]);await page.evaluate(async()=>{(await import('/js/core/api.js')).handleUnauthorized();});releaseLogs();releaseStatus();await pending;
  assert.equal(await page.locator('#ai-provider').textContent(),'—');assert.equal(await page.locator('#ai-state').textContent(),'로그아웃됨');
  assert.equal(await page.locator('#tab-btn-ai-analyzer').evaluate(el=>el.style.display),'none');assert.ok(!(await page.locator('#ai-logs-body').textContent()).includes('onerror'));
  await page.unroute(logs);await page.unroute(status);
  await page.locator('#login-username').fill('viewer');await page.locator('#login-password').fill(fixture.password);await page.getByRole('button',{name:'로그인',exact:true}).click();
  await page.locator('#login-overlay.hidden').waitFor({state:'attached'});
    await page.locator('#connection-status.connected').waitFor({state:'visible'});await page.locator('#tab-btn-ai-analyzer').click();
  await page.waitForFunction(()=>document.querySelector('#ai-state').textContent==='정지');
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:fixture.screenshot,fullPage:true});
  await page.locator('#btn-logout').click();await page.locator('#login-overlay:not(.hidden)').waitFor();
  assert.equal(await page.locator('#ai-provider').textContent(),'—');assert.equal(await page.locator('#tab-btn-ai-analyzer').evaluate(el=>el.style.display),'none');
  assert.deepEqual(errors,[]);console.log('ai browser checks passed');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
